packages:
  # client/ 경로 내부의 package.json 인식
  - 'client/**'
  # server/ 경로 내부의 package.json 인식
  - 'server/**'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # all packages in subdirs of pages/
  - 'pages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'